export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_PRODUCT_BASKET = 'GET_PRODUCT_BASKET';
export const REMOVE_PRODUCT_BASKET = 'REMOVE_PRODUCT_BASKET';
export const CHANGE_BASKET_COST = 'CHANGE_BASKET_COST';
export const CLEAR_BASKET = 'CLEAR_BASKET';



export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const GET_STATE = 'GET_STATE';
